# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Change project status on assignment

on:
  issues:
    types: [assigned]

jobs:
  update-project-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Project-Sound SDLC # Replace with your project name
          #issue-number: ${{ github.event.issue.number }}
          column: "Todo" # Replace with "To Do" or your column name
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}

